version: 2
executorType: machine
jobs:
  build:
    steps:
      - checkout

      - restore_cache:
          key: testcontainers-concord-{{ checksum "pom.xml" }}

      - run: ./mvnw -B dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: testcontainers-concord-{{ checksum "pom.xml" }}

      - run: ./mvnw -B clean install
