name: build

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

concurrency:
  group: ${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        jdk_version: [ '17' ]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '${{ matrix.jdk_version }}'
          distribution: 'temurin'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and test with Maven
        run: ./mvnw -B clean install
